export interface JobDTO {
  salesRepName?: any;
  name: string;
  address1: string;
  address2: string;
  city: string;
  faxNo: string | "";
  mobileNo: string | "";
  homeNo: string | "";
  officeNo: string | null;
  phoneNo: string | null;
  jobType: string | null;
  note: string | null;
  teamMememberId?: number[];
  relatedContactId?: number[];
  zip: number;
  startDate: string | Date;
  endDate: string | Date;
  description: string;
  stateId: number | null;
  salesRepsentativeId: number;
  lastStatusChangeDate: string | Date | null;
  primaryContactId: number | null;
  officeLocationId: number;
  workFlowId: number;
  subContractorId: number;
  timelineId: number;
  jobStatusId: number;
  leadSourceId: number | string;
  id: number;
  userId: number | null;
  createdBy: number;
  modifiedBy: number;
  companyId: number;
  createdDate: string;
  modifiedDate: string;
  isDeleted: boolean | null;
  jobStatus?: any;
  workFlow?: any;
  salesRepId: any;
}
